# Generated by Django 4.2 on 2023-04-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainteaseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='cover',
            field=models.JSONField(verbose_name='Cover'),
        ),
    ]
