# Generated by Django 4.2 on 2023-04-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainteaseapp', '0004_alter_deck_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='cover',
            field=models.JSONField(default=dict),
        ),
    ]
