# Generated by Django 4.2 on 2023-04-07 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brainteaseapp', '0005_alter_deck_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('front', models.JSONField(default=dict)),
                ('back', models.JSONField(default=dict)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brainteaseapp.deck')),
            ],
        ),
    ]
