# Generated by Django 4.2 on 2023-04-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainteaseapp', '0007_rename_back_card_backjson_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='converSVG',
            new_name='coverSVG',
        ),
        migrations.RemoveField(
            model_name='card',
            name='name',
        ),
        migrations.AddField(
            model_name='card',
            name='title',
            field=models.CharField(default='string', max_length=500, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
